# -*- coding: utf-8 -*-
"""BlockHouse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7aRKG9a6PXEQfIxGMncltRjg9cCjHwy
"""

# pip install databento

import databento as db
import pandas as pd
from datetime import datetime, timedelta
import warnings
import os

warnings.filterwarnings('ignore')

# Initialize the client with your API key
api_key = "db-SsrRd7PSWsqBSEvbp7bQS9tpMupxB"
client = db.Historical(api_key)

symbols=['AAPL', 'AMGN', "TSLA", "JPM", "XOM"]
dataset = "XNAS.ITCH"  # Dataset name
schema = "MBP-10"                  # Market by Price, 10 levels
start_date = "2024-12-02"          # Example start date
end_date = "2024-12-08"
output_dir = "order_book_csvs"
os.makedirs(output_dir, exist_ok=True)

for symbol in symbols:
    print(f"Fetching data for {symbol}...")
    try:
        # Fetch data
        data = client.timeseries.get_range(
            dataset=dataset,
            schema=schema,
            symbols=[symbol],
            start=start_date,
            end=end_date,
        )
        # Convert to Pandas DataFrame
        df = data.to_df()

        # Save to CSV
        file_path = os.path.join(output_dir, f"{symbol}_data.csv")
        df.to_csv(file_path, index=False)
        print(f"Data for {symbol} saved to {file_path}.")
    except Exception as e:
        print(f"Error fetching data for {symbol}: {e}")

print("Data fetching and saving completed.")

